### PR TITLE
Query timeout

### PR DESCRIPTION
**Pull request by hstern**

### CODE REVIEW

**Comment by edmonds** [comment]
I get the following warning when compiling the Cython'd code:

```
dnstable.c: In function ‘__pyx_pf_8dnstable_9iteritems_8__next__’:
dnstable.c:2696:3: warning: enumeration value ‘dnstable_res_success’ not handled in switch [-Wswitch]
```

That C code corresponds to this Cython code:

```Cython
        res = dnstable_iter_next(self._instance, &ent)
        if res == dnstable_res_failure:
            raise StopIteration
        elif res == dnstable_res_timeout:
            raise Timeout
        d = entry()
        d.from_c(ent, self.iszone)
        return d
```

(https://github.com/farsightsec/pydnstable/blob/query_timeout/dnstable.pyx#L160-L167)

At a glance that code looks correct as written; the problem comes from Cython's complimentary upgrade of the `if`/`elif` block into a `switch`/`case` block when it compiles the code to C.

However, we should still probably rewrite the code quoted above to explicitly handle `dnstable_res_success`, to make it more robust against the introduction of new `dnstable_res_*` values in the future. Maybe something like:

```Cython
        res = dnstable_iter_next(self._instance, &ent)
        if res == dnstable_res_success:
            d = entry()
            d.from_c(ent, self.iszone)
            return d
        elif res == dnstable_res_failure:
            raise StopIteration
        elif res == dnstable_res_timeout:
            raise Timeout
        else:
            raise DnstableException, "shouldn't happen"
```

**Comment by edmonds** [comment]
Hm, so, I can't actually get this code to work. `StopIteration` is being raised immediately after calling `.next()` on a query iterator that's just raised `Timeout`.

It looks like our `__next__()` function isn't even being called in that case, either.

**Comment by hstern** [comment]
I don't get this warning with Cython version 0.20.1post0.  Which version are you using?

**Comment by edmonds** [comment]
Ehh, this is version `0.19.1+git34-gac3e3a2-1~bpo70+1`, the one from wheezy-backports :-)

Don't worry about it, the enum warning is very minor.

**Pull request merged**
